const faq=[
{question:"Ile kosztuje budowa domu szkieletowego?",answer:"Koszt budowy zależy od powierzchni budynku, wybranego projektu, standardu wykończenia oraz lokalizacji inwestycji. Każdą wycenę przygotowujemy indywidualnie po zapoznaniu się z oczekiwaniami klienta"},
{question:"Czy dom szkieletowy nadaje się do całorocznego zamieszkania?",answer:"Tak. Prawidłowo wykonany i ocieplony dom szkieletowy zapewnia komfort mieszkania przez cały rok, zarówno zimą, jak i latem. Nowoczesne technologie izolacji pozwalają osiągnąć bardzo dobre parametry energetyczne."},
{question:"Z jakiego drewna wykonywana jest konstrukcja?",answer:"Do budowy wykorzystujemy drewno konstrukcyjne odpowiednio przygotowane do zastosowań budowlanych. Materiał jest dobierany tak, aby zapewnić stabilność, bezpieczeństwo i trwałość konstrukcji."},
{question:"Jakie etapy obejmuje budowa domu?",answer:"Proces realizacji obejmuje konsultację, przygotowanie wyceny, podpisanie umowy, wykonanie konstrukcji, montaż poszczególnych elementów budynku oraz odbiór gotowej inwestycji."},
{question:"Czy wykonujecie domy pod klucz?",answer:"Nie. Nasze domy budujemy wykończone, lecz po stronie inwestora jest fundament, instalacje wodno-kanalizacyjne, oraz instalacja elektryczna."},
{question:"Na jakim terenie realizujecie inwestycje?",answer:"Budujemy domy na terenie całej Polski, a także realizujemy transport i montaż konstrukcji dla klientów ze Słowacji, oraz Czech."},
{question:"Czy dom szkieletowy wymaga specjalnej  konserwacji?",answer:"Nie. Przy zastosowaniu odpowiednich materiałów i prawidłowym wykonaniu budynek nie wymaga bardziej skomplikowanej konserwacji niż dom murowany."},
{question:"Jak długo trwa budowa domu szkieletowego?",answer:"Technologia szkieletowa pozwala znacząco skrócić czas realizacji w porównaniu z budownictwem tradycyjnym. Termin wykonania zależy od wielkości domu, zakresu prac oraz warunków pogodowych."},
{question:"Czy dom szkieletowy jest trwały?",answer:"Tak. O trwałości domu decyduje jakość materiałów oraz poprawność wykonania. Konstrukcje szkieletowe są od wielu lat stosowane w krajach skandynawskich, Kanadzie i USA, gdzie służą kolejnym pokoleniom mieszkańców."},
{question:"Czy mogę zbudować dom według własnego projektu?",answer:"Tak. Realizujemy zarówno projekty indywidualne przygotowane przez architekta, jak i projekty gotowe, które można dostosować do własnych potrzeb."},
{question:"Czy pomagacie w formalnościach związanych z  budową?",answer:"Tak. Doradzamy klientom w kwestiach formalnych związanych z realizacją inwestycji i pomagamy przygotować się do rozpoczęcia budowy."},
{question:"Czy dom szkieletowy jest energooszczędny?",answer:"Tak. Dzięki nowoczesnym rozwiązaniom izolacyjnym domy szkieletowe charakteryzują się niskim zapotrzebowaniem na energię potrzebną do ogrzewania budynku."},
{question:"Czy mogę zobaczyć wcześniejsze realizacje?",answer:"Tak. Zachęcamy do zapoznania się z galerią realizacji oraz do kontaktu w celu uzyskania dodatkowych informacji o wykonanych projektach."},
{question:"Czy można rozbudować dom szkieletowy w  przyszłości?",answer:"Tak. Technologia szkieletowa umożliwia stosunkowo łatwą rozbudowę lub przebudowę budynku, jeśli w przyszłości pojawi się taka potrzeba."},
{question:"Jak rozpocząć współpracę z TASBUD?",answer:"Wystarczy skontaktować się z nami telefonicznie lub poprzez formularz kontaktowy. Po wstępnej rozmowie przygotujemy indywidualną ofertę i odpowiemy na wszystkie pytania dotyczące inwestycji."},
{question:"Ile trwa montaż domu?",answer:"Montaż domu trwa zwykle od 2 do 5 dni. Wszystko zależy od specyfikacji projektu."},
{question:"Ile za m² powierzchni zabudowy?",answer:"Cena za m² zależna jest od wielkości oraz specyfikacji budynku. Ceny za dom rekreacyjny zaczynają się od 2000zł/m2, a za dom mieszkalny od 3500zł/m²."},
{question:"Czy wykonujecie fundament?",answer:"Nie. Wykonanie fundamentu jest po stronie inwestora"},
{question:"Dlaczego warto wybrać TASBUD?", answer: "TASBUD specjalizuje się w budowie domów drewnianych z wysokiej jakości materiałów i indywidualnym podejściem do każdego klienta." },
{question: "Czy wykonujecie domy według indywidualnego projektu?", answer: "Tak. Budujemy według projektów gotowych oraz indywidualnych." },
{question:"Jak długo trwa budowa domu?", answer: "Przygotowanie elementów domu trwa kilka tygodni, a sam montaż od 1-5 dni,w zależności rodzaju i specyfikacji domu" },
{question:"Czy budujecie domy na zgłoszenie?", answer: "Tak. Większość naszych naszych domów jest na zgłoszenie " },
{question:"Z jakiego drewna budowane są domy?", answer: "Nasze domy są budowane z drewna świerkowego. Konstrukcja budynków jest wykonana z certyfikowanego drewna C24" },
{question:"Czy drewno jest czterostronnie strugane?", answer: "Tak. Drewno w naszych domach jest czterostronnie strugane" },
{question:"Jakie ocieplenie ścian oferujecie?", answer: "Ściany naszych domów głównie są ocieplone wełną mineralną, wszystko jest zależne od indywidualnej preferencji inwestora." },
{question:"Jakie ocieplenie dachu oferujecie?", answer: "Dachy naszych domów głównie są ocieplone wełną mineralną, wszystko jest zależne od indywidualnej preferencji inwestora." },
{question:"Jakie ocieplenie podłogi oferujecie?", answer: "Podłogi naszych domów głównie są ocieplone styropianem." },
{question:"Czy dom nadaje się do całorocznego użytkowania?", answer: "Tak. Domy wybudowane przez Naszą firmę nadają się do całorocznego użytkowania." },
{question:"Czy wykonujecie domki rekreacyjne?", answer: "Tak. W ofercie są domy rekreacyjne." },
{question:"Czy można zmienić układ pomieszczeń?", answer: "Tak. Układ pomieszczeń jest ustalany indywidualnie." },
{question:"Czy wykonujecie tarasy?", answer: "Tak. W ofercie naszch domów są dodatkowe tarasy. Istnieje możliwość zamówienia samego tarasu." },
{question:"Czy wykonujecie zadaszenia?", answer: "Tak. Do naszych domów można domówić zadaszenie. Istnieje możliwość zamówienia samego zadaszenia." },
{question:"Czy montujecie okna?", answer: "Tak. Wszystkie domy z naszej ofery są wyposażone w okna." },
{question:"Czy montujecie drzwi zewnętrzne?", answer: "Tak. Wszystkie domy z naszej ofery są wyposażone w drzwi zewnętrzne." },
{question:"Czy wykonujecie elewację drewnianą?", answer: "Tak. Wszystkie domy z naszej ofery posiadają elewację drewnianą." },
{question:"Czy wykonujecie instalację elektryczną?", answer: "Nie. Możemy pomóc w poszukaniu firmy, która wykona instalację elektryczną." },
{question:"Czy wykonujecie instalację wodno-kanalizacyjną?", answer: "Nie. Możemy pomóc w poszukaniu firmy, która wykona instalację wodno-kanalizacyjną." },
{question:"Czy wykonujecie instalację grzewczą?", answer: "Nie. Możemy pomóc w poszukaniu firmy, która wykona instalację grzewczą." },
{question:"Jak wygląda wycena?", answer: "Każda wycena przygotowywana przez TASBUD jest indywidualnie, ponieważ koszt budowy domu zależy od wielu czynników.Aby przygotować dokładną ofertę, potrzebujemy projektu domu lub podstawowych informacji dotyczących planowanej inwestycji." },
{question:"Czy wycena jest bezpłatna?", answer: "Tak. Wycena domu jest bezpłatna." },
{question:"Jak przebiega budowa?", answer: "Dom przyjeżdża na miejsce budowy w elementach przygotowanych wcześniej. Budowa domu trwa od 2-5 dni." },
{question:"Czy można odwiedzić budowę?", answer: "Tak. Inwestor może być podczas budowy domu." },
{question:"Czy udzielacie gwarancji?", answer: "Tak. Na nasze domu jest udzielana gwarancja." },
{question:"Jak długo trwa gwarancja?", answer: "Gwarancja na nasze domy udzielana jest na 2 lata. Po okresie gwarancyjnym również pomagamy w razie potrzeby" },
{question:"Czy dom jest energooszczędny?", answer: "Tak. Dzięki odpowiedniej izolacji, szczelnej konstrukcji i nowoczesnym materiałom nasze domy są energooszczędne oraz zapewniają niskie koszty ogrzewania przez cały rok." },
{question:"Czy dom drewniany jest trwały?", answer: "Tak. Odpowiednio zaprojektowany i wykonany dom drewniany może służyć przez wiele dziesięcioleci, zachowując swoje właściwości i estetyczny wygląd." },
{question:"Jak konserwować elewację?", answer: "Elewację drewnianą należy regularnie czyścić oraz odnawiać powłokę ochronną zgodnie z zaleceniami producenta. Dzięki temu drewno zachowuje trwałość i estetyczny wygląd przez wiele lat." },
{question:"Jak ogrzewać dom drewniany?", answer: "Dom drewniany można ogrzewać na różne sposoby. Głównym czynnikiem wyboru ogrzewania są preferencje inwestora." },
{question:"Czy montujecie pompę ciepła?", answer: "Nie. Możemy pomóc w znalezieniu firmy która zamontuje pompę ciepła." },
{question:"Czy montujecie rekuperację?", answer: "Nie. Możemy pomóc w znalezieniu firmy która zamontuje rekuperację." },
{question:"Czy montujecie klimatyzację?", answer: "Nie. Możemy pomóc w znalezieniu firmy która zamontuje klimatyzację." },
{question:"Czy można wykonać antresolę?", answer: "Tak. Stodoła z naszej oferty posiada antresolę. W większości modeli naszych domow można wykonać antresolę." },
{question:"Czy można wykonać poddasze użytkowe?", answer: "Tak. Większość domów z naszej oferty posiada poddasze użytkowe." },
{question:"Czy wykonujecie garaże?", answer: "Tak. Możemy wybudować garaż." },
{question:"Czy wykonujecie wiaty?", answer: "Tak. W domach budowanych przez naszą firmę można wykonać wiatę. Istnieje możliwość wybudowania wiaty wolnostojącej." },
{question:"Czy wykonujecie pergole?", answer: "Tak. Możemy wykonać pergole." },
{question:"Czy pomagacie wybrać projekt?", answer: "Tak. Staramy się jak najlepiej doradzić naszym klientom. Przeprowadzamy wywiad aby dostosować projekt do indywidualnych potrzeb." },
{question:"Czy można finansować budowę kredytem?", answer: "Nie udzielamy kredytów." },
{question:"Jakie są terminy realizacji?", answer: "Termin realizacji zależy od wybranego projektu, zakresu prac oraz aktualnego harmonogramu. Po przygotowaniu oferty przedstawiamy orientacyjny termin rozpoczęcia i zakończenia budowy." },
{question:"Czy cena może się zmienić?", answer: "Po podpisaniu umowy cena inwestycji nie ulega zmianie." },
{question:"Co obejmuje cena domu?", answer: "Cena domu zależy od wybranego standardu wykonania. Każda wycena jest przygotowywana indywidualnie i dokładnie określa, co obejmuje oferta, dzięki czemu klient od początku zna zakres realizacji i koszty." },
{question:"Czy można zamówić stan surowy?", answer: "Tak. Można zamówić dom w stanie surowym." },
{question:"Czy można zamówić stan deweloperski?", answer: "Nie. Istnieje możliwość wykonania domu do stanu deweloperskiego, pod warunkiem, że inwestor zorganizuje firmy które zrobią instalacje." },
{question:"Czy budujecie małe domy do 70 m²?", answer: "Tak. W naszej ofercie znajdują się domy do 70 m²." },
{question:"Czy budujecie nowoczesne stodoły?", answer: "Tak. W naszej ofercie znajduje się nowoczesna stodoła. Projekt domu można dowolnie modyfikować." },
{question:"Czy oferujecie wizualizacje?", answer: "Nie. Nie oferujemy wizualizacji." },
{question:"Czy wykonujecie schody?", answer: "Tak. W domach z poddaszem użytkowym oraz antresolą schody drewniane są w cenie domu." },
{question:"Czy montujecie rynny?", answer: "Tak. Montujemy rynny PVC." },
{question:"Czy stosujecie membrany dachowe?", answer: "Tak. We wszystkich naszych domach są zastosowane membrany dachowe." },
{question:"Jakie okna polecacie?", answer: "Standard oraz producent okien zależą od wybranego projektu i indywidualnych ustaleń. Oferujemy wysokiej jakości okna o bardzo dobrych parametrach termoizolacyjnych." },
{question:"Jakie drzwi polecacie?", answer: "Wewnątrz montujemy drzwi drewniane wyprodukowane przez naszą firmę. Drzwi zewnętrzne zależą od wybranego projeku i indywidualnych ustaleń." },
{question:"Czy budujecie domy z antresolą?", answer: "Tak. W ofercie znajdują się domy z antresolą. Przykładem jest Stodoła." },
{question:"Czy można rozbudować dom?", answer: "Tak. Dom drewniany w łatwy sposób można rozbudować w przyszłości." },
{question:"Czy wykonujecie domy inwestycyjne?", answer: "Tak. Budujemy domy inwestycyjne przeznaczone na wynajem krótkoterminowy, długoterminowy oraz cele rekreacyjne. Chętnie doradzimy rozwiązanie dopasowane do planowanej inwestycji." },
{question:"Czy można obejrzeć realizacje?", answer: "Nasze realizacje można obejrzeć w zakładce Realizacje, oraz na żywo w siedzibie firmy, która znajduje się w Jordanowie." },
{question:"Czy wykonujecie projekty indywidualne?", answer: "Tak. Zakres realizacji zależy od projektu i indywidualnych ustaleń. Chętnie doradzimy najlepsze rozwiązanie oraz przygotujemy szczegółową ofertę." },
{question:"Jak rozpocząć współpracę?", answer: "Skontaktuj się z nami telefonicznie lub przez formularz kontaktowy. Omówimy Twoje potrzeby, przygotujemy indywidualną wycenę i przeprowadzimy Cię przez kolejne etapy realizacji." },
{question:"Czy budujecie na działkach rekreacyjnych?", answer: "Tak. Budujemy domy na działkach rekreacyjnych." },
{question:"Czy stosujecie certyfikowane drewno?", answer: "Tak. Do budowy wykorzystujemy wysokiej jakości drewno konstrukcyjne, spełniające obowiązujące normy oraz pochodzące ze sprawdzonych źródeł." },
{question:"Czy dom spełnia normy WT?", answer: "Tak. Nasze domy projektowane są i wykonywane zgodnie z obowiązującymi przepisami oraz wymaganiami Warunków Technicznych (WT), z uwzględnieniem wybranego standardu wykonania." },
{question:"Jak wygląda płatność?", answer: "Płatnośc wygląda następująco. Pierwsze zaliczka, na 7 dni przed planowanym montażem zapłata za całość domu, montaż w trakcie budowy domu." },
{question:"Czy można wprowadzać zmiany?", answer: "Tak. Każdy dom z oferty można dowolnie modyfikować." },
];
